### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/draft-guide-microprofile-reactive-messaging-rest#12]
It is unclear how you bridge imperative to reactive from someone who is completely new in this area. This guide needs to be rewritten when the new MicroProfile Reactive Messaging is released because it will introduce a mean to achieve this. I see you utilised Emitter from RxJava to achieve this in the meanwhile.
Please provide a graph to demonstrate the flow and explain each step according to the graph. Exaplain the way how to bridge imperative to reactive via referencing the code snippet.

**Comment by Emily-Jiang** [comment]
> The application in this guide consists of two microservices, system and inventory. Every 15 seconds, the system microservice calculates and publishes events that contain its current average system load. The inventory microservice subscribes to that information so that it can keep an updated list of all the systems and their current system loads. The inventory microservice also subscribes to a POST request response that queries a specific system property on the system microservice. The current inventory of systems can be accessed via the /systems REST endpoint. You’ll create the system and inventory microservices using MicroProfile Reactive Messaging. Please refer to the figure below.

I think you should introduce RxJava here as in the later section you have to rely on it.

**Comment by MaiHameed** [comment]
> This guide needs to be rewritten when the new MicroProfile Reactive Messaging is released because it will introduce a mean to achieve this.

We'll be publishing the guide using RxJava as the bridge, and will update the guide accordingly when the new MPRM is released.

> Please provide a graph to demonstrate the flow and explain each step according to the graph.

I'm not sure what you mean by provide a graph, we already have the following diagram to demonstrate the flow: 
![image](https://user-images.githubusercontent.com/26514093/85462905-04d31e80-b574-11ea-8993-167f6cececd1.png)

Is there anything in particular that you feel is missing? Could you elaborate?

> Explain the way how to bridge imperative to reactive via referencing the code snippet.

We referenced the code snippet in the `Creating the inventory microservice` section here:
![image](https://user-images.githubusercontent.com/26514093/85463339-862ab100-b574-11ea-84aa-5cdc36154916.png)

With hotspots to the corresponding lines in the associated `InventoryResource.java` file. Could you elaborate on what you think is missing? Thanks!

**Comment by MaiHameed** [comment]
I added the RxJava explanation in this commit: https://github.com/OpenLiberty/draft-guide-microprofile-reactive-messaging-rest/commit/14e568aa0395c9247f0edb0aa75564e2a9587adb if you could take a quick look and let me know if it's sufficient :)

**Comment by Emily-Jiang** [comment]
@MaiHameed I cannot see the diagram from here. I am not sure where the diagram ends up with. Do you have a different view somewhere?

**Comment by Emily-Jiang** [comment]
More comments:
reactive Java services => reactive microservices

**Comment by MaiHameed** [comment]
I changed `reactive Java services` to `reactive Java microservices`, is that fine or should I change it to just `reactive microservices`?

**Comment by MaiHameed** [comment]
@Emily-Jiang There's an explanation of the RxJava methods/classes used in the paragraph starting with `When accessed...` here in the guide: http://lgdev1.fyre.ibm.com:4020/guides/microprofile-reactive-messaging-rest.html#creating-the-inventory-microservice if you could take a look and let me know if it's sufficient please :)

**Comment by MaiHameed** [comment]
All comments have been addressed and merged, closing.
