### ISSUE TITLE
Feedback from content review

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-microprofile-reactive-messaging-rest#17]
The guide should focus on aspects directly related to handling of messages/events in REST services.  While the guide needs to be modular and standalone, it doesn't need to cover or focus on building reactive microservices.

- Consider a title like "Sending and receiving events in RESTful microservices".  Abstract, front matter and introduction should be updated accordingly.
  - Introduction i.e. "What you'll learn" needs to be much more concise in general;
  - e.g. Do we need to cover RxJava in "What you'll learn"?

- Consider starting with covering the inventory service describing what is needed in a REST service to produce and consume messages integrating with an event streaming platform like Kafka.

- Then, call out the events processor in the system microservice.  This is a unique aspect in this guide though it's more reactive than REST-reactive integration.

- MP RM configuration should or can be optional.  Possible to make this an inspection alone since there isn't anything special in terms of REST-reactive integration.

- Section titles should reflect the focus or what users will accomplish in the sections.

Tagging @lauracowen if she has additional feedback.  Cc @gkwan-ibm @GraceJansen @jamiecoleman92

**Comment by yeekangc** [comment]
Additional feedback:

- Style inconsistent with guides in general (if I am not mistaken; see _italics_)
  - _This guide_ helps you write microservices so that when a user hits the RESTful endpoint, producer events are generated.
  - _Most importantly_, you’ll learn how to bridge the gap between reactive applications and RESTful ones.
  - _Before you go any further, it is highly recommended to go through the basic guide._

- There isn't a POST request for inventory service?

> The inventory microservice also subscribes to a POST request response that queries a specific system property on the system microservice.

- Can link to other reactive guides besides the testing one?

**Comment by MaiHameed** [comment]
> e.g. Do we need to cover RxJava in "What you'll learn"?

This was suggested by @Emily-Jiang in this issue: https://github.com/OpenLiberty/draft-guide-microprofile-reactive-messaging-rest/issues/12#issuecomment-648020795. Let me know if you still think it should be removed.

**Comment by yeekangc** [comment]
It's reasonable to cover what is relevant for RxJava.  Then, it may not be necessary to do that under "What you'll learn".  Key is to ensure focus for the guide and the Intro section should reflect that.

**Comment by MaiHameed** [comment]
I opened a PR addressing all of your comments @yeekangc here #18. The newest site update can be found [here](http://lgdev1.fyre.ibm.com:4020/guides/microprofile-reactive-messaging-rest.html) and the old version is still live [here](https://draft-guides.mybluemix.net/guides/microprofile-reactive-messaging-rest.html). Let me know if there are any further issues :)

**Comment by yeekangc** [comment]
The Intro section in the latest draft available at https://github.com/OpenLiberty/draft-guide-microprofile-reactive-messaging-rest still needs work.  It needs to be consistent with the title, abstract and communicate the focus/intention of the guide appropriately.

**Comment by MaiHameed** [comment]
Addressed with #19 and #20. Let me know if there are still any issues.
