### ISSUE TITLE
ID review feedback

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/draft-guide-microprofile-reactive-messaging-rest#22]
I added ID review feedback to the attached Word doc. Let me know if you have any questions! 

[restful-reactive-guide.docx](https://github.com/OpenLiberty/draft-guide-microprofile-reactive-messaging-rest/files/4982988/restful-reactive-guide.docx)

**Comment by MaiHameed** [comment]
Thanks for the review @Charlotte-Holt! Just a couple of clarifications:

> I think we should make “Emitter” monospaced in this paragraph. It’s capitalized in this instance and maybe we want to highlight that it’s an RxJava interface. 

Monospaced by using `backticks` correct? And you just wanted the Emitter in RxJava `Emitter` highlighted not the whole thing?

> In “Replace the inventory/microprofile-config.properties file” and “Replace the system/microprofile-config.properties file.”, should the file names be monospaced?

We typically leave it as is across guides.

> •	Should we update the following paragraphs to match the paragraphs in the Testing the application section of the “Creating reactive Java microservices” guide:

The only difference is this sentence which is in the "reactive Java microservices" guide:

> After the application is up and running, you can access the application by making a GET request to the `/systems` endpoint
of the `inventory` service.

Which I updated this guide to reflect. All other sentences are the same, so I left them unchanged.

I opened a PR #23 if you could quickly review it please :)

**Comment by MaiHameed** [comment]
Closed with #23 thanks!

**Comment by Charlotte-Holt** [comment]
@MaiHameed 

>Monospaced by using backticks correct? And you just wanted the Emitter in RxJava Emitter highlighted not the whole thing?

Yep! Just "Emitter" in "RxJava Emitter". Thx!

>Which I updated this guide to reflect. All other sentences are the same, so I left them unchanged.

Great, thanks!
