### ISSUE TITLE
Peer Review - Mac

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/draft-guide-microprofile-reactive-messaging-rest#5]
## Peer Review conducted on 3 platforms: Mac, Windows & Linux
- Mac OS is our base OS as the dev content team generally develops on the Mac OS.
- Conduct three separate peer reviews for each OS. 

Peer Review: review to be done by a peer member. 

Functionality
---
- [x] Check that the guide has working instructions and sample code
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 

Formatting & Presentation
---

`README.adoc` checks:
- [x] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
- [x] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check that the pom.xml, server.xml, etc files are clean
    - [x] Remove any dependencies and features that are not required
    - [x] Ensure that the parent pom.xml files do not contain any dependencies, and all dependencies are specified in the children pom.xml files
- [x] Examples with the right outcomes are provided
- [ ] Example with the wrong outcomes, if any, are provided

`pom.xml` checks (if files are present):
- [x] Check that the file follows the template found here: https://github.com/OpenLiberty/draft-guides-template/blob/master/finish/pom.xml
- [x] Check that the following dependencies are included in all of the `pom.xml` files:
```
<!-- Provided dependencies -->
<dependency>
  <groupId>jakarta.platform</groupId>
  <artifactId>jakarta.jakartaee-api</artifactId>
  <version>8.0.0</version>
  <scope>provided</scope>
</dependency>

<dependency>
  <groupId>org.eclipse.microprofile</groupId
  <artifactId>microprofile</artifactId>
  <version>3.3</version>
  <type>pom</type>
  <scope>provided</scope>
</dependency>
```
- [x]  Check that the versions of plugins are directly provided and not fed in by a file property.
  - Not formatted like so:
```
    <properties>
        <!-- Plugins -->
        <version.liberty-maven-plugin>3.2</version.liberty-maven-plugin>
    </properties>

    <!-- Liberty plugin -->
    <plugin>
        <groupId>io.openliberty.tools</groupId>
        <artifactId>liberty-maven-plugin</artifactId>
        <version>${version.liberty-maven-plugin}</version>
    </plugin>
```
  - Should be formatted like so:
```
    <!-- Liberty plugin -->
    <plugin>
        <groupId>io.openliberty.tools</groupId>
        <artifactId>liberty-maven-plugin</artifactId>
        <version>3.2</version>
    </plugin>
```
- [x] Check that there are 4 spaces per indent for proper formatting
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable

Overall checks:
- [x] Check the consistency of guide with the template and other guides
- [x] Check the quality of code according to the best coding practices
- [x] Check that all licensing statements are properly stated in all files, with the correct year (Should be present in all Java files + the `index.html`)
- [x] Check that the directories are properly structured
- [ ] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide
- [x] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

---

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [x] Additional tests where applicable: 
    - [x] Define test coverage and review with team (including guide contributor, if available)
    - [x] Define detail test cases 
    - [x] Consider corner cases targeting the specific guide
    - [x] Consider corner cases UI tests
    - [x] Consider testing URL on all browsers, ie, FF, Chrome, Safari
    - [x] Consider testing the `curl` command for URL visits
- [x] Consider building with both Maven and Gradle build tools 
- [x] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [ ] Run Acrolinx Checker on draft (above 70 score approximately)
- [ ] Consider SEO title and description for the guides 
- [ ] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
    - [x] Table of contents 
    - [x] Headings
    - [x] Paragraphs
    - [x] code snippets
    - [x] outputs
    - [x] links
    - [x] hotspots 
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by NimG98** [comment]
- [ ] Change title to:
    - "Trigger messages in **a** reactive Java microservice via RESTful endpoints"
    - or "Trigger messages in reactive Java microservice**s** via RESTful endpoints"
    - [ ] change the description to have similar changes

## What you'll learn
- [ ] Add "The" at the start of the sentence
    > Current implementation of MicroProfile Reactive Messaging operates on continuous streams of events.
- [ ] Change "E.g." to "For example," or "For instance,"
    > E.g. Producer produces events periodically, and Customer consumes those events.
- [ ]  change `invetory` to `inventory`
    > The `invetory` microservice also subscribes to a POST request

## Creating the system microservice
- [ ] change `sendProperty` to `sendProperty()`
- [ ] `sendProperty` hotspot should highlight just function and not annotations as well
    > The `system` microservice contains a method named `sendProperty`.
- [ ] remove "the" before Kafka (or add a word after Kafka like "messaging system", etc.)
    > calculates the requested property on the fly and publishes it back to the Kafka over
- [ ] `sendSystemLoad()` hotspot should highlight just function and not annotations as well
- [ ] too keep consistent with `@Outgoing` annotation mentioned before this sentence, change `@Outgoing`  to `@Outgoing("systemLoad")` 
    > The `@Outgoing` annotation on the `sendSystemLoad()` method

## Creating the inventory microservice
- [ ] change "rxJava" to "RxJava"
    > The `Flowable.create()` method from rxJava is used to
- [ ] keep instances of `Publisher` consistent. In the previous section it was `Publisher`. And in this section it is "Publisher" or "publisher"
    ![image](https://user-images.githubusercontent.com/46586499/81411673-b2978480-9110-11ea-9e94-8a73c8ac0f7c.png)

## Configuring the MicroProfile Reactive Messaging connectors for Kafka
- [ ] change "microservices" to "microservice"
    > in the Kafka message broker so that the `inventory` microservices can consume the messages.
- [ ] put a file hotspot on `microprofile-config.properties` directing to that file
    > The `inventory` microservice uses a similar `microprofile-config.properties` configuration to define its required incoming stream.

## Building and running the application
- [ ] i think "system" should be `system` with backticks
    > For simplicity, the script starts one instance of the system service.

## Testing the application
- [ ] i think it's fine but just mentioning that when i clicked `http://localhost:9085/inventory/systems` the first couple of times it was giving an empty list `[ ]`, but it was fine after waiting a few more secs
    - maybe tell them to wait before clickign the url
- [ ] change formatting after "For example"
    ![image](https://user-images.githubusercontent.com/46586499/81412768-59305500-9112-11ea-9419-52bb5f748dbb.png)

    - remove comma and leave ":", then put "The..." on the next line
- [ ] I got confused that that `http://localhost:9085/inventory/systems/property/os.name` wasn't available yet. And doesn't explain why you are making a POST request
    - Maybe tell them that for this property to be available in the inventory, you need to first send a POST request to the service to add `os.name` to the set of properties.
- [ ] Also after making the POST successfully and having `os.name` in the `http://localhost:9085/inventory/systems` url, the url `http://localhost:9085/inventory/systems/property/os.name` was still showing nothing. So the sentence "The `http://localhost:9085/inventory/systems/property/os.name` URL will give you the `os.name` value for your system." doesn't make sense

**Comment by NimG98** [comment]
## Other
- [ ] in index.html change `JSON-B` to `JavaScript Object Notation Binding 1.0` and any other features should match the exact name that is listed as the title on their doc
- [ ] link guide to Travis CI
- [ ] add guide to draft daily build automation
- [ ] also shouldn't the prefix of the repo be `draft-guide` right now
- [ ] no page tags being shown. to see the page tags being shown, need to add guide under [guides-common/guide_tags.json](https://github.com/OpenLiberty/guides-common/blob/master/guide_tags.json) on dev branch, and then refresh draft site to see the page tags

**Comment by ankitagrawa** [comment]
> too keep consistent with @Outgoing annotation mentioned before this sentence, change @Outgoing to @Outgoing("systemLoad")
> 
>     The @Outgoing annotation on the sendSystemLoad() method

Here we are talking about annotation. In the previous paragraph it was a channel. Hence this should be @Outgoing

> change "rxJava" to "RxJava" 

The library is rxJava. Also keeping it consistent with other guides and SME feedback.

@NimG98

**Comment by NimG98** [comment]
All feedback addressed
