### ISSUE TITLE
SME feedback

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/draft-guide-microprofile-reactive-messaging-rest#6]
This looks mostly ok but I have a few questions.

In `InventoryResponse.getSystemProperty()` you've annotated your method with `@POST` and set `@Consumes(MediaType.APPLICATION_JSON)` but you never do anything with the request body. Usually in a POST request, the data for the request is sent in the body, not in the path.

Sending a POST to `/systems/property/propertyName` results in a message being sent to the `propertyNameTopic` topic. This will then get picked up by _only one_ of the system microservices (assuming they all have the same config and hence the same group.id) which will send back a response message with its hostname and the property value.

This doesn't sound like what you want. I'm not sure what you're expecting to happen when there's more than one system microservice.

A few more things which might make the code more readable:

 In `InventoryResource` rename `private FlowableEmitter<String> property;` to something like `propertyRequestEmitter` or `propertyNameEmitter`.

I would also rename your topics and channels across the application so that they better convey the purpose of the things they hold. Possibly something like `propertyRequest` and `propertyResponse` would make more sense than `getProperty` and `setProperty`.

In the guide:
> The properties of this channel are defined in the `microprofile-config.properties` file.

"Property" has become a bit of an overloaded term because your example is sending messages with properties back and forth. Maybe say "The configuration for this channel is defined in the `microprofile-config.properties` file".

**Comment by yeekangc** [comment]
@MaiHameed @gkwan-ibm, have we resolved the above?

**Comment by MaiHameed** [comment]
The guide went through a major update after this review, and addressed all of the comments:

> In InventoryResponse.getSystemProperty() you've annotated your method with @POST and set @Consumes(MediaType.APPLICATION_JSON) but you never do anything with the request body. Usually in a POST request, the data for the request is sent in the body, not in the path.In InventoryResponse.getSystemProperty() you've annotated your method with @POST and set @Consumes(MediaType.APPLICATION_JSON) but you never do anything with the request body. Usually in a POST request, the data for the request is sent in the body, not in the path.

The `POST` request has been updated to `PUT` and the data for the request is sent in the post body.

> Sending a POST to /systems/property/propertyName results in a message being sent to the propertyNameTopic topic. This will then get picked up by only one of the system microservices (assuming they all have the same config and hence the same group.id) which will send back a response message with its hostname and the property value.

The guide only asks the user to spin up one instance of the `system` service, and has a note on how to ensure the message is sent to all `system` instances if present by setting unique `group.id`s.

> In InventoryResource rename private FlowableEmitter<String> property; to something like propertyRequestEmitter or propertyNameEmitter.

> I would also rename your topics and channels across the application so that they better convey the purpose of the things they hold. Possibly something like propertyRequest and propertyResponse would make more sense than getProperty and setProperty.

Done.

> In the guide:

The properties of this channel are defined in the microprofile-config.properties file.

"Property" has become a bit of an overloaded term because your example is sending messages with properties back and forth. Maybe say "The configuration for this channel is defined in the microprofile-config.properties file".

Updated
