### ISSUE TITLE
Dev content review for revisied change to PUT endpoint

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-microprofile-reactive-messaging-rest#8]
- [ ] update the diagram
- **Creating the system microservice**
  - [x] `@Incoming("getProperty")` -> `@Incoming("propertyRequest")`
  - [x] `@Outgoing("setProperty")` -> `@Outgoing("propertyResponse")`
  - Last statement "The messages are transported ..." 
    - [x] `setProperty` -> `propertyResponse`
    - [x] add `propertyRequest`
  - [x] comment "# setProperty stream" and "# getProperty stream" in the system mp properties file need to be updated
- **Creating the inventory microservice**
  - [x] `@Incoming("propertyMessage")` -> `@Incoming("addSystemProperty")`
  - [x] need to update "... when a property name is sent in a POST request to the /systems/property endpoint." to
    - "... when a property name is sent in a PUT request to the /data endpoint."
  - [x] "...from the POST request..." -> "...from the PUT request..."
  - [x] `@Outgoing("propertyName")` -> `@Outgoing("requestSystemProperty")`
  - [x] "...`propertyName` stream ..." -> "...`requestSystemProperty` stream ..."
  - [x] comment "# propertyMessage stream" and "# propertyName stream" in the inventory mp properties file need to be updated
- **Configuring the MicroProfile Reactive Messaging connectors for Kafka**
  - [x] "...and `setProperty` channel,..." to "...and `propertyResponse` channel,..."
  - [x] "...`propertyMessageTopic` topic, ..." to "...`addSystemPropertyTopic` topic, ..." for system mp properties
  - [x] `group.id` need to highlight a line
  - [x] "...`propertyMessageTopic` topic, ..." to "...`addSystemPropertyTopic` topic, ..." for inventory mp properties
  - [x] need to mention requestSystemProperty
- **Testing the application**
  - [x] If the curl command same in 3 platforms, no need to have OS tabs

**Comment by gkwan-ibm** [comment]
@MaiHameed fyi^

**Comment by MaiHameed** [comment]
> update the diagram

How and to what?

> add propertyRequest

Not sure what this means/entails

> group.id need to highlight a line 

Which one? The system config properties file has one, inventory has two

**Comment by MaiHameed** [comment]
Addressed, closing.
